// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvowjmmragnhayhdoant.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2b3dqbW1yYWduaGF5aGRvYW50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTkwNDAsImV4cCI6MjA2MDYzNTA0MH0.AGFz5lAv1ldI8wuiqRWbHC6hC_IDi7iv2BN5HmEhI8E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);